### ISSUE TITLE
Why is Yannick not a member?

### ISSUE THREAD

**Issue by PFigs** [tutgnss/GNSS_visualization_tools#7]
@Yanickdefrance I don't see you in the total channel contributors. Please try to fix it. Here's something that might help

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by Yanickdefrance** [comment]
Hi,

That's strange cause I can see myself...

2016-07-03 18:58 GMT+03:00 Pedro Figueiredo e Silva <
notifications@github.com>:

**Comment by PFigs** [comment]
Check your email (spam), it seems you haven't accepted the invitation to join the org.
